[package]
name = "lush"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
mlua = { version = "0.11.5", features = ["luajit"] }
regex = "1.12.3"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
debug = "limited"
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3
